### PR TITLE
added meta viewport to improve responsiveness in mobile devices

### PR DESCRIPTION
**Pull request by msatul1305**

### CODE REVIEW

**Comment by rashil2000** [comment]
Hey @msatul1305, the addition works. But the footer is not showing properly and is covering up some content in mobile devices. Please look into it.

**Comment by rashil2000** [comment]
Screenshot (94)
Look at the box.

**Comment by mukul-mehta** [comment]
Hey Atul, I believe it would be better if you just added a hyperlink rather than adding the URL since it's more readable and looks better imo. 

What say @rashil2000

**Comment by rashil2000** [comment]
Cool. Change it to 
`<a href="https://github.com/rashil2000/d-syfer" target="__blank">github.com/rashil2000/d-syfer</a>`
in all the pages.

**Comment by msatul1305** [comment]
@rashil2000 I have fixed the footer overlap problem . Please recheck.

**Comment by rashil2000** [comment]
The issue persists, on other pages. It'd be better if you do this.

> Cool. Change it to
> `<a href="https://github.com/rashil2000/d-syfer" target="__blank">github.com/rashil2000/d-syfer</a>`
> in all the pages.

**Comment by msatul1305** [comment]
done @rashil2000

**Comment by rashil2000** [comment]
Nice! @msatul1305

**Pull request merged**
