### PR TITLE
add Aafine cipher

### PR DESCRIPTION
**Pull request by jai-dewani**

### CODE REVIEW

**Comment by rashil2000** [comment]
Change the text on the banner.

**Comment by rashil2000** [comment]
You changed the banner on the wrong file.

**Comment by jai-dewani** [comment]
Changed the banner on the correct file and the wrong file.

**Comment by rashil2000** [comment]
Hey, I went through the JS file now, and I'd like to ask about/change certain things: 

- [ ] You are converting the entire input to lowercase, This shouldn't happen, all the other ciphers preserve the case of the text (I guess just removing the toLowerCase function on line 40 in script3.js would do).

- [ ] The function multiplicative_inverse is erronous. For the most part, it returns the same array. Try console.logging it.

- [ ] What is the multiplicative inverse function actually doing? You haven't used it anywhere (apart from line 43, that's just a declaration). Multiplicative inverse would be used if we were deciphering back. If you'd like to add that feature, you are welcome to. 

- [ ] The textarea with id cipher - line 54, index3.html - says "Wbsh khuh", which is the Caesar cipher for "Type here". It should actually say "Zyfc rcpc", the Affine cipher for "Type here".

- [ ] Try including a higher resolution alternative for affine.png. The current one gets stretched and doesn't look good.

**Comment by mukul-mehta** [comment]
@jai-dewani Any updates?

**Comment by jai-dewani** [comment]
> * [x]  You are converting the entire input to lowercase, This shouldn't happen, all the other ciphers preserve the case of the text (I guess just removing the toLowerCase function on line 40 in script3.js would do).  

Did the same

> * [x]  The function multiplicative_inverse is erronous. For the most part, it returns the same array. Try console.logging it.  
> * [x]  What is the multiplicative inverse function actually doing? You haven't used it anywhere (apart from line 43, that's just a declaration). Multiplicative inverse would be used if we were deciphering back. If you'd like to add that feature, you are welcome to.  

I have removed the multiplicative_inverse function as it was supposed to be used for decrypting but there is no use of it in this case.

> * [x]  The textarea with id cipher - line 54, index3.html - says "Wbsh khuh", which is the Caesar cipher for "Type here". It should actually say "Zyfc rcpc", the Affine cipher for "Type here".

Added the same to the textarea

> * [x]  Try including a higher resolution alternative for affine.png. The current one gets stretched and doesn't look good.

Changed the images in the page, have a look and let me know if they are apt or not

**Comment by rashil2000** [comment]
@jai-dewani Everything looks good. Just keep the older mul.svg, and remove the other images. One image is fine.

**Comment by jai-dewani** [comment]
I didn't notice it earlier but the older mul.svg depicts the decryption method for affine cipher which is not really needed in this case.

**Comment by rashil2000** [comment]
Hmm. Then remove affine_for.jpg, and keep affine.jpg.

**Comment by rashil2000** [comment]
Hey @jai-dewani , any updates?

**Comment by rashil2000** [comment]
The time for evals is near.

**Comment by jai-dewani** [comment]
Removed affine_for.jpg

**Comment by rashil2000** [comment]
@jai-dewani Please update your repository first.

**Comment by jai-dewani** [comment]
Updated

**Pull request merged**
